package Universite;

/**
* Universite/BookHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Universite.idl
* Tuesday, 17 December 2024 13:09:15 o'clock CET
*/

public final class BookHolder implements org.omg.CORBA.portable.Streamable
{
  public Universite.Book value = null;

  public BookHolder ()
  {
  }

  public BookHolder (Universite.Book initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Universite.BookHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Universite.BookHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Universite.BookHelper.type ();
  }

}
