package Universite;


/**
* Universite/Book.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Universite.idl
* Tuesday, 17 December 2024 13:09:15 o'clock CET
*/

public final class Book implements org.omg.CORBA.portable.IDLEntity
{
  public String nomLivre = null;

  // Book name
  public String auteur = null;

  // Author of the book
  public String collection = null;

  // Book collection/series
  public String datePublication = null;

  public Book ()
  {
  } // ctor

  public Book (String _nomLivre, String _auteur, String _collection, String _datePublication)
  {
    nomLivre = _nomLivre;
    auteur = _auteur;
    collection = _collection;
    datePublication = _datePublication;
  } // ctor

} // class Book
