package Universite;


/**
* Universite/Epreuve.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Universite.idl
* Tuesday, 17 December 2024 13:09:15 o'clock CET
*/

public final class Epreuve implements org.omg.CORBA.portable.IDLEntity
{
  public String nomEpreuve = null;

  // Name of the exam
  public float note = (float)0;

  // Score for the exam
  public float coefficient = (float)0;

  public Epreuve ()
  {
  } // ctor

  public Epreuve (String _nomEpreuve, float _note, float _coefficient)
  {
    nomEpreuve = _nomEpreuve;
    note = _note;
    coefficient = _coefficient;
  } // ctor

} // class Epreuve
