package Universite;

/**
* Universite/EpreuveHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Universite.idl
* Tuesday, 17 December 2024 13:09:15 o'clock CET
*/

public final class EpreuveHolder implements org.omg.CORBA.portable.Streamable
{
  public Universite.Epreuve value = null;

  public EpreuveHolder ()
  {
  }

  public EpreuveHolder (Universite.Epreuve initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Universite.EpreuveHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Universite.EpreuveHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Universite.EpreuveHelper.type ();
  }

}
