package Universite;

/**
* Universite/EtudiantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Universite.idl
* Tuesday, 17 December 2024 13:09:15 o'clock CET
*/


// Etudiant interface with attributes and methods
public final class EtudiantHolder implements org.omg.CORBA.portable.Streamable
{
  public Universite.Etudiant value = null;

  public EtudiantHolder ()
  {
  }

  public EtudiantHolder (Universite.Etudiant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Universite.EtudiantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Universite.EtudiantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Universite.EtudiantHelper.type ();
  }

}
