package Universite;

/**
* Universite/PromotionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Universite.idl
* Tuesday, 17 December 2024 13:09:15 o'clock CET
*/


// Promotion interface
public final class PromotionHolder implements org.omg.CORBA.portable.Streamable
{
  public Universite.Promotion value = null;

  public PromotionHolder ()
  {
  }

  public PromotionHolder (Universite.Promotion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Universite.PromotionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Universite.PromotionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Universite.PromotionHelper.type ();
  }

}
