package Universite;


/**
* Universite/PromotionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Universite.idl
* Tuesday, 17 December 2024 13:09:15 o'clock CET
*/


// Promotion interface
public interface PromotionOperations 
{
  void ajouter_un_etudiant (String nom, String prenom, int numEtudiant);

  // Use long here
  Universite.Etudiant rechercher_un_etudiant (int numEtudiant);

  // Use long here
  float calculer_moyenne_de_la_promotion ();
} // interface PromotionOperations
