package Universite;


/**
* Universite/StringListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Universite.idl
* Tuesday, 17 December 2024 13:09:15 o'clock CET
*/


// Define a sequence for a list of strings (e.g., exam names)
public final class StringListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StringListHolder ()
  {
  }

  public StringListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Universite.StringListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Universite.StringListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Universite.StringListHelper.type ();
  }

}
